#!/bin/bash
if [[ "$1" = "--version" ]]; then
  echo "${TARGET}-g++ (GCC) 13.2 20230727 (prerelease)"
  echo "Copyright (C) 2023 Free Software Foundation, Inc."
  echo "This is free software; see the source for copying conditions.  There is NO"
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
else
  # theargs=
  exec $thecxx -Wno-unknown-warning-option "${@/-fno-var-tracking-assignments/}"
  # exec $thecxx "$theargs"
fi
