#!/bin/bash
#!/usr/bin/env bash
if [[ "$1" = "--version" ]]; then
else
  exec $thecc -Wno-unknown-warning-option "${@/-fno-var-tracking-assignments/}"
  # exec $thecc "$theargs"
fi
bin_dir=`dirname "$0"`
if [ "$1" != "-cc1" ]; then
    "$bin_dir/clang" --target=${TARGET}-linux-android${API} "$@"
else
    # Target is already an argument.
    "$bin_dir/clang" "$@"
fi
