#!/bin/bash
#!/usr/bin/env bash
# theargs=
exec $thecxx -Wno-unknown-warning-option "${@/-fno-var-tracking-assignments/}"
# exec $thecxx "$theargs"

bin_dir=`dirname "$0"`
if [ "$1" != "-cc1" ]; then
    "$bin_dir/clang++" --target=${TARGET}-linux-android${API} "$@"
else
    # Target is already an argument.
    "$bin_dir/clang++" "$@"
fi

